### PR TITLE
Update inferno to fix inaccurate flamegraph

### PR DESCRIPTION
**Pull request by shanempope**
Flamegraphs were missing most leaves in the current inferno 0.8.0, updating it to 0.11.X fixed the issue.

### CODE REVIEW

**Comment by shanempope** [comment]
`cargo build` went wild on the lock file, I assume because this repo is so old. I'm not sure how to do a lighter touch.

**Comment by dalehamel** [comment]
We verified this in two ways:

- Patched reap to output folded stacks, piped them directly to `inferno-flamegraph`. On the latest version, we can see all of the reference chains. On version 0.8.0 used by reap, a lot are missing (but still show up in the textual summary).
- Bumping the dep in reap also fixes the issue

**Comment by djudd** [comment]
Thanks for finding and fixing this!

I'm fine with bumping a bunch of deps at once as long as the tests pass.

I didn't realize anyone was actively using this; I hope it's been helpful!

**Comment by dalehamel** [comment]
> I didn't realize anyone was actively using this; I hope it's been helpful!

It is, very cool tool! The algorithm is very clever. We have been using it to analyze ~3GB heap files, and it is able to do it impressively fast (~1-2 minutes on a M1 macbook pro). I originally thought it must have been missing some data, but the output of the folded stack lines was and always has been correct, just the older version of that library that mishandled them.

Thanks for the awesome tool!

**Comment by shanempope** [comment]
Thank you! We used it to find a memory leak or two. :)

**Comment by shanempope** [comment]
Sorry to bother again, @djudd is it easy to ship this fix to https://crates.io/crates/reap ?

**Comment by djudd** [comment]
Done! Sorry, thought I'd done that already.

**Pull request merged**
